//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon3genRNGLibrary.Frontier.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokemon3genRNGLibrary.Frontier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///  { &quot;class&quot;: &quot;たんぱんこぞう&quot;, &quot;name&quot;: &quot;トキヒト&quot;, &quot;matching&quot;: [&quot;ボクは&quot;, &quot;ぜったい&quot;, &quot;まけ&quot;, &quot;ません&quot;, &quot;…!&quot;], &quot;win&quot;: [&quot;ボク&quot;, &quot;つよい&quot;, &quot;でしょー!&quot;, &quot;へへ&quot;], &quot;lose&quot;: [&quot;あれ&quot;, &quot;…&quot;, &quot;?&quot;, &quot;なんで&quot;, &quot;?&quot;], &quot;pool&quot; : 0}, 
        ///  { &quot;class&quot;: &quot;たんぱんこぞう&quot;, &quot;name&quot;: &quot;ヒロミチ&quot;, &quot;matching&quot;: [&quot;わーい&quot;, &quot;かち&quot;, &quot;でも&quot;, &quot;まけ&quot;, &quot;でも&quot;, &quot;たのしい&quot;], &quot;win&quot;: [&quot;わーい&quot;, &quot;かって&quot;, &quot;&quot;, &quot;たのしい&quot;, &quot;なあ&quot;], &quot;lose&quot;: [&quot;わーん!!&quot;, &quot;&quot;, &quot;&quot;, &quot;やっぱり&quot;, &quot;くやしい&quot;, &quot;なあ&quot;], &quot;pool&quot; : 0}, 
        ///  { &quot;class&quot;: &quot;たんぱんこぞう&quot;, &quot;name&quot;: &quot;モトヨシ&quot;, &quot;matching&quot;: [&quot;おい&quot;, &quot;きみ&quot;, &quot;!!&quot;, &quot;ボクが&quot;, &quo... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string frontierTrainers {
            get {
                return ResourceManager.GetString("frontierTrainers", resourceCulture);
            }
        }
    }
}
